version: "3"
services:
  web:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    ports:
      - 3000:3000
    image:
      vijayakrishnajava/app-react
    volumes:
      - /app-redis/node_modules
      - ./src:/app-redis/src
      - ./public:/app-redis/public
    container_name: 'app-react-1'
