version: "3"
services:
  web:
    build: .
    ports:
      - 80:80
    image:
      vijayakrishnajava/app-react
    volumes:
      - /app-redis/node_modules
      - ./src:/app-redis/src
      - ./public:/app-redis/public
    container_name: 'app-react-1'
